<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="66" started-at="2019-07-20T07:39:29Z" finished-at="2019-07-20T07:39:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="66" started-at="2019-07-20T07:39:29Z" finished-at="2019-07-20T07:39:30Z">
      <class name="LogicTest.TestNG1">
        <test-method status="PASS" signature="test3()[pri:0, instance:LogicTest.TestNG1@20e2cbe0]" name="test3" duration-ms="15" started-at="2019-07-20T07:39:30Z" finished-at="2019-07-20T07:39:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="FAIL" signature="test2()[pri:1, instance:LogicTest.TestNG1@20e2cbe0]" name="test2" duration-ms="6" started-at="2019-07-20T07:39:30Z" finished-at="2019-07-20T07:39:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nand] but found [Anand]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nand] but found [Anand]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at LogicTest.TestNG1.test2(TestNG1.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test1()[pri:2, instance:LogicTest.TestNG1@20e2cbe0]" name="test1" duration-ms="2" started-at="2019-07-20T07:39:30Z" finished-at="2019-07-20T07:39:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- LogicTest.TestNG1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
